
package za.co.pps.auth.endpoints.tam;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SOAPFormatException", targetNamespace = "http://PPS.co.za/PPS_TAMAuth_Service/")
public class SOAPFormatException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SOAPFormatException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SOAPFormatException_Exception(String message, SOAPFormatException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SOAPFormatException_Exception(String message, SOAPFormatException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: za.co.pps.auth.endpoints.tam.SOAPFormatException
     */
    public SOAPFormatException getFaultInfo() {
        return faultInfo;
    }

}
